// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Services
{
    public int ServiceId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string MethodType { get; set; }

    public decimal? Price { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<TreatmentBooking> TreatmentBookings { get; set; } = new List<TreatmentBooking>();
}