// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class TreatmentBooking
{
    public int BookingId { get; set; }

    public int? UserId { get; set; }

    public int? DoctorId { get; set; }

    public int? ServiceId { get; set; }

    public DateTime? BookingDate { get; set; }

    public string Status { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual ICollection<MedicalRecord> MedicalRecords { get; set; } = new List<MedicalRecord>();

    public virtual Services Service { get; set; }

    public virtual ICollection<TreatmentSchedule> TreatmentSchedules { get; set; } = new List<TreatmentSchedule>();

    public virtual User User { get; set; }
}