// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class MedicalRecord
{
    public int RecordId { get; set; }

    public int? BookingId { get; set; }

    public DateTime? VisitDate { get; set; }

    public string Notes { get; set; }

    public string TestResults { get; set; }

    public int? DoctorId { get; set; }

    public virtual TreatmentBooking Booking { get; set; }

    public virtual Doctor Doctor { get; set; }
}