// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class TreatmentSchedule
{
    public int ScheduleId { get; set; }

    public int? BookingId { get; set; }

    public DateTime? EventDate { get; set; }

    public string EventType { get; set; }

    public string Description { get; set; }

    public bool? Reminder { get; set; }

    public virtual TreatmentBooking Booking { get; set; }
}