// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class VwTreatmentStat
{
    public string MethodType { get; set; }

    public int? TotalTreatments { get; set; }

    public int? AverageRating { get; set; }
}